### ISSUE TITLE
"/usr/bin/env: node --harmony: No such file or directory" on running melkor on ubuntu

### ISSUE THREAD

**Issue by kodikos** [hiddentao/melkor#12]
Hiya,

I was trying to set up melkor to run as a service under a vagrant cloud server build of ubuntu 14.04. There's a problem with the shebang that you use in your shell script because different flavours of unix handle the shebang differently (http://stackoverflow.com/questions/4303128/how-to-use-multiple-arguments-with-a-shebang-i-e). It's not easy to work out what's going on because most attempts to google the error message you get just talk about node not being installed correctly.
I don't think you need to fix this, unless you really need melkor to work better across 'nixes out of the box. Hopefully people should find this issue and fix it on their own systems. I just wrote a wrapper script as a fix:
#!/bin/bash
nodejs --harmony /usr/bin/melkor $*

**Comment by hiddentao** [comment]
Fixed.
