### ISSUE TITLE
Image support?

### ISSUE THREAD

**Issue by sg-s** [hiddentao/melkor#14]
Hi, is image upload possible?

**Comment by hiddentao** [comment]
Not at the moment through the web UI. You'd have to manually add it to
the wiki folder and then commit it.

On 26/01/2015 09:45, Srinivas Gorur-Shandilya wrote:
>
> Hi, is image upload possible?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hiddentao/melkor/issues/14>.
>


-- 
Ramesh Nair

Freelance Web Developer

www.hiddentao.com
www.github.com/hiddentao

**Comment by sg-s** [comment]
thanks. any plans for the future?

**Comment by hiddentao** [comment]
Not in the near future, no. I don't have a pressing need for it myself. PR's welcome though.
