### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by sventer** [hiddentao/melkor#16]
I cannot install Melkor on Windows 7 machine. I get the following error when trying to install

gyp ERR! build error
gyp ERR! stack Error: `msbuild` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (E:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "E:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\StevenDev\AppData\Roaming\npm\node_modules\melkor\node_modules\slug\node_modules\unicode\node_modules\bufferstream\node_modules\buffertool
s
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok
npm WARN optional dep failed, continuing buffertools@2.1.2

**Comment by hiddentao** [comment]
Sorry I don't have a  Windows machine so I can't test this. But from the looks it seems that you're running Node 0.12 - I'm aware that some of the native modules (that need `node-gyp`) don't yet work on 0.12. So I would recommend using 0.11 for now.

**Comment by sventer** [comment]
Thanks

I installed version 0.11 and now Melkor is installed. But now I have the same issue as this one

https://github.com/hiddentao/melkor/issues/13

**Comment by hiddentao** [comment]
Fixed.
